
version: "3"

services: 

    
  mongo:
    image: mongo
    hostname: database 
    volumes: 
      - ./database:/db
    container_name: database
    ports:
      - "27017:27017"

  back:
    image: abdelrahmankh/back:last
    hostname: back
    ports:
      - "5000:5000"
    volumes: 
      - ./back:/back
    container_name: back

    depends_on: 
      - mongo

  front:
    image: abdelrahmankh/front:last
    volumes: 
      - ./front:/front
    container_name: front
    ports: 
      - "8080:8080"
    depends_on: 
      - back

  # volumes:
  # mongo-data:
  #   driver: local
